# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22c20ec17f5d31249587b3879bf045872ad977913fd3e6cf304780b1eaff92b6e9784dd2ce91db6fef74003ccfe91961eaf9a15b4ebc03f0e2ac161f7a575323

test:
  secret_key_base: 91b6da0ad09e092f54771eb2f0702274083fb64ccd5f4bb6414a7fc2c22f147416d01c69da7b2023167bdd77b4f80c83e2ae5d5ec3d26056830c4abeb86b8537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
